[package]
name = "inbox-script"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webpage = "1.6.0"
url = "2.4.0"
linkify = "0.9.0"
